# Generated by Django 4.2.16 on 2024-11-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("seats", models.IntegerField()),
                (
                    "description",
                    models.CharField(
                        default="No description available", max_length=255
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="number_of_people",
            new_name="guests",
        ),
        migrations.AddField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.table",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("table", "date", "time")},
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="updated_at",
        ),
    ]
