# Generated by Django 4.2.16 on 2024-11-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_alter_reservation_guests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="guests",
            field=models.IntegerField(),
        ),
    ]
