# Generated by Django 4.2.16 on 2024-09-23 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0002_table_rename_number_of_people_reservation_guests_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="description",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reservations.table"
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.CharField(max_length=50),
        ),
    ]
